spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bevocms
    username: postgres
    password: test1234@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

dedipass:
  publicKey: a8978e7273a1dc358a8577766e66df3e
  privateKey: 289128c12d95714a3c43fb883bf435fe1bc84553
upload:
  url: http://localhost:8080/images/get
  admin:
    dir: images
  dir: skins